### ISSUE TITLE
DS_storeファイルが混在

### ISSUE THREAD

**Issue by togawa28** [paoon/mao_webpage#1]
DS_storeはよくわからんがそのディレクトリ内にあるファイルのメタ情報を格納するMac特有の隠しファイルらしい。
http://uxmilk.jp/48160
web page作成には全く関係ないので削除してOK。
削除する際はゴミ箱に入れた後に`git rm .DS_store`とするとステージングに上がってcommitできます。

**Comment by togawa28** [comment]
```
git rm .DS_Store
git commit -m 'DS_Storeを削除'
git push origin master
```

**Comment by paoon** [comment]
指示に従って .DS_Store を削除しました！

**Comment by togawa28** [comment]
ちゃんと消えてるね ナイス！
