### ISSUE TITLE
togawa28がpushできない

### ISSUE THREAD

**Issue by togawa28** [paoon/mao_webpage#4]
誰にでも好き勝手pushされちゃうと困るので、レポジトリを作った人はCollaboratorsとして「この人にはpush権を与えます」と明示しなきゃいけない

上のタブのsettings → 左のタブからCollaborators → togawa28で検索してAdd

**Comment by paoon** [comment]
指示どうりに操作して、togawa28をCollaboratorにしました！

**Comment by togawa28** [comment]
ありがとう！
これで俺もpushできます
